### ISSUE TITLE
Run keeper plugin not logging

### ISSUE THREAD

**Issue by dennispipper** [ttscoff/Slogger#228]
Using the latest version of slogger and the latest runkeeper app for
iPhone on iOS 7, it appears that it something isn't working. It ran all Sept and Oct. the plugin no longer logs my runs since Nov 2

**Comment by jgclark** [comment]
I've tried to get it working today, and I'm getting errors from just this plugin.

First, here's the relevant part of my config file:

RunkeeperLogger:
  runkeeper_description:
  - Gets runkeeper activity information
  RunkeeperLogger_last_run: Sat May  9 23:11:02 2015
  runkeeper_access_token: 44497c5d3643471983a870261d24557a
  runkeeper_tags: '#run #runkeeper'
  runkeeper_save_data_file: /Users/jonathan/Dropbox/m/runkeeper.txt
  metric_distance: true

And then here are the error logs when running just this plugin:

> ./slogger -o runkeeper
Initializing Slogger v2 (2.1.14)...
/Library/Ruby/Gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/jonathan/Library/Scripts/slogger/plugins/runkeeper.rb:58:in `do_log'
	from /Users/jonathan/Library/Scripts/slogger/slogger.rb:284:in `block in run_plugins'
	from /Users/jonathan/Library/Scripts/slogger/slogger.rb:271:in `each'
	from /Users/jonathan/Library/Scripts/slogger/slogger.rb:271:in `run_plugins'
	from /Users/jonathan/Library/Scripts/slogger/slogger.rb:460:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./slogger:18:in `<main>'

**Comment by jgclark** [comment]
I've now looked at the first few pages of the RunKeeper API pages, and I'm no expert in all of this, but it seems that this plugin isn't going to work against the current API. For starters it currently requires OAuth 2.0, and this codebase doesn't mention that at all. Is anyone using this plugin happily still?

**Comment by ats** [comment]
The plugin itself doesn't handle obtaining your authorization key, so 
you need to do that separately. There is a link to some instructions for 
this in the plugin's header. Once that's inserted to the plugin 
configuration, it should work --- at least, it remains working fine for 
me. I'm not aware of updates on the Runkeeper side that would have 
broken or threaten to break anything.

Alan

**Comment by jgclark** [comment]
Thank you, Alan. I realised I'd only followed half of the auth instructions, and so then got it working OK. I then deleted this comment, and changed an earlier one to say that it was now fine. I'm sorry that you got this before my updates!

Regards,

-- Jonathan

    _____________________________

**Comment by ats** [comment]
I can't tell you how long I spent screwing with getting the auth part to work the first time. I've always been able to get oauth sorted out via curl nonsense, but it just wouldn't work for me with Runkeeper, so I built that dumb request form, and that did the trick. It still seems finicky, but seems to have worked for enough other folks. I'm glad you were able to get it up and running, too. Cheers.
