### ISSUE TITLE
Problems installing fitbit

### ISSUE THREAD

**Issue by Pixelbelichter** [ttscoff/Slogger#309]
Hi,

Slogger runs very fine for me! (I´m only using the Omnifocus Feature so far).
Today i tried to install the fitbit feature. 

> sudo gem install fitgem
> Successfully installed fitgem-0.9.0
> Parsing documentation for fitgem-0.9.0
> 1 gem installed

When running ./slogger --update-config it gives me the following error:

Initializing Slogger v2.1 (2.1.0.11)...
/Users/USER/Documents/SW/Slogger/plugins/fitbit.rb:34:in `require': cannot load such file -- fitgem (LoadError)
    from /Users/USER/Documents/SW/Slogger/plugins/fitbit.rb:34:in`<top (required)>'
    from /Users/USER/Documents/SW/Slogger/slogger.rb:267:in `require'
    from /Users/USER/Documents/SW/Slogger/slogger.rb:267:in`block in run_plugins'
    from /Users/USER/Documents/SW/Slogger/slogger.rb:259:in `each'
    from /Users/USER/Documents/SW/Slogger/slogger.rb:259:in`run_plugins'
    from /Users/USER/Documents/SW/Slogger/slogger.rb:446:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from ./slogger:18:in`<main>'

Any Ideas? Thanks for your help!

**Comment by martinstreicher** [comment]
This broke for me again today when running `bundle update` and fitgem went `Installing fitgem 0.12.0 (was 0.10.0)`.
