### ISSUE TITLE
InstapaperLogger not working. Feed doesn't validate?

### ISSUE THREAD

**Issue by Zettt** [ttscoff/Slogger#326]
InstapaperLogger doesn't seem to be working either. When I run it, the plugin doesn't log any activity. I checked and this could be an Instapaper issue, or a Slogger issue.

First of all, Instapaper gives a wrong RSS feed address which looks like this: 

```
http://www.instapaper.com//archive/rss/user-id/unique-id
```

Notice the double `//`. Gladly the RSS URL also gives an XML result without. Slogger gives the following output for `./slogger --onlyrun InstapaperLogger`:

```
InstapaperLogger: Getting Instapaper posts for 71 accounts
/Users/me/.Slogger/plugins/instapaperlogger.rb:49:in `do_log': undefined method `each' for #<String:0x000001023d4778> (NoMethodError)
    from /Users/me/.Slogger/slogger.rb:284:in `block in run_plugins'
    from /Users/me/.Slogger/slogger.rb:271:in `each'
    from /Users/me/.Slogger/slogger.rb:271:in `run_plugins'
    from /Users/me/.Slogger/slogger.rb:447:in `<top (required)>'
    from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/me/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from ./slogger:18:in `<main>'
```

**Comment by griffey** [comment]
Instapaper is currently throwing the same set of errors for me as above...curious why this was closed when it appears the same error still occurs.
