### ISSUE TITLE
Instagram plugin complains about missing rake gem and doesn't open the browser

### ISSUE THREAD

**Issue by zxaos** [ttscoff/Slogger#339]
On Yosemite, ruby 2.1.3, attempting to run the instagram plugin throws an error complaining about a missing rake Gem. Bundler shows the gem as being installed.

```
./slogger -o instagram
Initializing Slogger v2 (2.1.14)...
  17:55:09      InstagramLogger: Instagram requires configuration, please run from the command line and follow the prompts

------------- Instagram Configuration --------------

Slogger will now open an authorization page in your default web browser. Copy the code you receive and return here.

Press Enter to continue (You may have to hit refresh once in the browser)...

/Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/spec_set.rb:85:in `map!'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/spec_set.rb:85:in `materialize'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/definition.rb:132:in `specs'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/definition.rb:177:in `specs_for'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/definition.rb:166:in `requested_specs'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/environment.rb:18:in `requested_specs'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/runtime.rb:13:in `setup'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler.rb:122:in `setup'
  from /Users/zxaos/.gem/ruby/2.1.3/gems/bundler-1.7.10/lib/bundler/setup.rb:17:in `<top (required)>'
  from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'



------------- Authentication Started -------------

Paste the code you received here: ^C/opt/slogger/plugins/instagram.rb:76:in `gets': Interrupt
  from /opt/slogger/plugins/instagram.rb:76:in `gets'
  from /opt/slogger/plugins/instagram.rb:76:in `do_log'
  from /opt/slogger/slogger.rb:284:in `block in run_plugins'
  from /opt/slogger/slogger.rb:271:in `each'
  from /opt/slogger/slogger.rb:271:in `run_plugins'
  from /opt/slogger/slogger.rb:460:in `<top (required)>'
  from /Users/zxaos/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/zxaos/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from ./slogger:18:in `<main>'
```

```
bundle show
Gems included by the bundle:
  * addressable (2.3.6)
  * buftok (0.2.0)
  * bundler (1.7.10)
  * crack (0.4.2)
  * descendants_tracker (0.0.4)
  * diff-lcs (1.2.5)
  * equalizer (0.0.9)
  * faraday (0.9.0)
  * faraday_middleware (0.9.1)
  * feed-normalizer (1.5.2)
  * hashie (3.3.2)
  * hpricot (0.8.6)
  * http (0.5.1)
  * http_parser.rb (0.6.0)
  * instagram (1.1.3)
  * json (1.8.1)
  * memoizable (0.4.2)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * multi_json (1.10.1)
  * multipart-post (2.0.0)
  * nokogiri (1.6.5)
  * oauth (0.4.7)
  * rack (1.6.0)
  * rack-protection (1.5.3)
  * rake (10.4.2)
  * rspec (3.1.0)
  * rspec-core (3.1.7)
  * rspec-expectations (3.1.2)
  * rspec-mocks (3.1.3)
  * rspec-support (3.1.2)
  * safe_yaml (1.0.4)
  * simple-rss (1.3.1)
  * simple_oauth (0.2.0)
  * sinatra (1.4.5)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * twitter (5.3.1)
  * twitter_oauth (0.4.94)
  * vcr (2.9.3)
  * webmock (1.20.4)
```

Other plugins, including the twitter one on which the instagram plugin seems to be based, work correctly.

**Comment by larryhynes** [comment]
I'm not sure `bundle show` lists *installed* gems, though I could be wrong. (I'm assuming it just lists the gems that would be installed by the current bundle. Like I say, I could be wrong!) You might try `bundle check` or just go with a `bundle install` in the slogger directory.

**Comment by zxaos** [comment]
This is directly after running bundle install. Bundle check reports all dependencies satisfied.

**Comment by larryhynes** [comment]
Ah, OK. What, for curiosity's sake, does `rake --version` return?

**Comment by stevebutterworth** [comment]
I also have this exact problem, the right version of rake is there but get this error when trying to setup instagram

**Comment by stevebutterworth** [comment]
Ah worked it out. You don't want to be hardcoding the path to the ruby binary.
