### ISSUE TITLE
Twitterlogger - accepts oath but they won't run

### ISSUE THREAD

**Issue by MarwoodChap** [ttscoff/Slogger#352]
New install on Yosemite.

I've edited the plugin with the details for the two accounts I'd like to track. 
Then updated the config via `./slogger --update-config`

I then get the following error, which has me a bit foxed.
```00:09:56        TwitterLogger: Getting Twitter timeline for marwoodchap
/Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:74:in `get_tweets': undefined method `configure' for Twitter:Module (NoMethodError)
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:237:in `block (2 levels) in do_log'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:262:in `try'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:237:in `block in do_log'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:235:in `each'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:235:in `do_log'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:284:in `block in run_plugins'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:271:in `each'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:271:in `run_plugins'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:460:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./slogger:18:in `<main>'```

**Comment by MarwoodChap** [comment]
This is my config file. Other than the twitter issue and a problem with the Goodreads xml URL, which I have yet to look at again, it all *seems* to be working OK

```---
storage: /Users/jamesmarwood/Dropbox/Apps/Day One/Journal.dayone
image_filename_is_title: true
date_format: '%F'
time_format: '%R'
last_run_time: Sun Feb  1 00:09:23 2015
FacebookIFTTTLogger:
  description:
  - Parses Facebook posts logged by IFTTT.com
  - facebook_ifttt_input_file is a string pointing to the location of the file created
    by IFTTT.
  - The recipe at https://ifttt.com/recipes/56242 determines that location.
  FacebookIFTTTLogger_last_run: Sun Feb  1 00:09:23 2015
  facebook_ifttt_input_file: /Users/jamesmarwood/Dropbox/AppData/ifttt/facebook/facebook.md.txt
  facebook_ifttt_star: false
  facebook_ifttt_tags: '#social #blogging'
FlickrLogger:
  flickr_description:
  - Logs today's photos from Flickr.
  - flickr_ids is an array of one or more IDs
  - flickr_datetype can be the "upload" or "taken" date to be used
  - Get your Flickr ID at <http://idgettr.com/>
  - Get your Flickr API key at <http://www.flickr.com/services/apps/create/noncommercial/>
  FlickrLogger_last_run: Sun Feb  1 00:09:23 2015
  flickr_api_key: ab535d374a62a74a899765811787dd66
  flickr_ids:
  - 30993871@N00
  flickr_datetype: upload
  flickr_tags: '#social #photo'
FoursquareLogger:
  description:
  - foursquare_feed must refer to the address of your personal feed.
  - Your feed should be available at <https://foursquare.com/feeds/>
  FoursquareLogger_last_run: Sun Feb  1 00:09:24 2015
  foursquare_feed: https://feeds.foursquare.com/history/FRSI5EUIJWVH4EG2ZD4YJDEX4JSZJ4CH.rss
  foursquare_tags: '#social #checkins'
GoodreadsLogger:
  description:
  - goodreads_save_image will save the book cover as the main image for the entry
  - goodreads_feed is a string containing the RSS feed for your read books
  - goodreads_star_posts will create a starred post for new books
  - 'goodreads_tags are tags you want to add to every entry, e.g. "#social #reading"'
  GoodreadsLogger_last_run: Sun Feb  1 00:09:25 2015
  goodreads_feed: www.goodreads.com/review/list_rss/3869786
  goodreads_save_image: false
  goodreads_star_posts: false
  goodreads_tags: '#social #reading'
InstagramLogger:
  description:
  - Logs your posts from Instagram
  - No real setup required beyond needing to authenticate with the Instagram API.
  - backdate (true/false) gives you the option to add the 20 most recent photos to
    Day One.
  InstagramLogger_last_run: Sun Feb  1 00:05:59 2015
  tags: '#social #instagram'
  backdate: false
  access_token: ''
InstapaperLogger:
  instapaper_description:
  - Logs today's posts to Instapaper.
  - instapaper_feeds is an array of one or more RSS feeds
  - Find the RSS feed for any folder at the bottom of a web interface page
  InstapaperLogger_last_run: Sun Feb  1 00:07:47 2015
  instapaper_feeds:
  - http://www.instapaper.com/rss/184791/82bhqcjhjxRnPtK2BSaxuj3mw
  instapaper_include_content_preview: true
  instapaper_tags: '#social #reading'
OmniFocusLogger:
  omnifocus_description:
  - Grabs completed tasks from OmniFocus
  - omnifocus_folder_filter is an optional array of folders that should be included.
    If left empty, all tasks will be imported.
  OmniFocusLogger_last_run: Sun Feb  1 00:07:47 2015
  omnifocus_tags: '#tasks'
  omnifocus_save_hashtags: true
  omnifocus_completed_tasks: true
  omnifocus_log_notes: false
  omnifocus_folder_filter: []
TwitterLogger:
  description:
  - Logs updates and favorites for specified Twitter users
  - twitter_users should be an array of Twitter usernames, e.g. [ ttscoff, markedapp
    ]
  - save_images (true/false) determines whether TwitterLogger will look for image
    urls and include them in the entry
  - save_favorites (true/false) determines whether TwitterLogger will look for the
    favorites of the given usernames and include them in the entry
  - save_images_from_favorites (true/false) determines whether TwitterLogger will
    download images for the favorites of the given usernames and include them in the
    entry
  - save_retweets (true/false) determines whether TwitterLogger will include retweets
    in the posts for the day
  - 'droplr_domain: if you have a custom droplr domain, enter it here, otherwise leave
    it as d.pr '
  - oauth_token and oauth_secret should be left blank and will be filled in by the
    plugin
  TwitterLogger_last_run: Sun Feb  1 00:07:47 2015
  twitter_users:
  - marwoodchap
  - howfatisjames
  save_favorites: true
  save_images: true
  save_images_from_favorites: true
  droplr_domain: d.pr
  twitter_tags: '#social #twitter'
  oauth_token: 8702002-rFuQxKswj1vMB2yjvy2Bj3x7YcgCHkvKDC0ZvJuk
  oauth_token_secret: 99oqZJeIV4SLKRNQHacGKJwrL4AlzzvBMvgeLMLQ
  exclude_replies: true
```

**Comment by ttscoff** [comment]
Try bundle update again. It looks like it might be using an incorrect Twitter gem. 

- Brett

**Comment by MarwoodChap** [comment]
Thanks Brett -I just tried that but am getting the same error.

Bundle Update gets me twitter 5.3.1

```
Jamess-Mac-mini:slogger-master jamesmarwood$ bundle update
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using addressable 2.3.6
Using buftok 0.2.0
Using safe_yaml 1.0.4
Using crack 0.4.2
Using thread_safe 0.3.4
Using descendants_tracker 0.0.4
Using diff-lcs 1.2.5
Using digest 0.0.1
Using equalizer 0.0.9
Using multipart-post 2.0.0
Using faraday 0.9.1
Using faraday_middleware 0.9.1
Using hpricot 0.8.6
Using simple-rss 1.3.1
Using feed-normalizer 1.5.2
Using hashie 3.3.2
Using http_parser.rb 0.6.0
Using http 0.5.1
Using multi_json 1.10.1
Using instagram 1.1.3
Using json 1.8.2
Using memoizable 0.4.2
Using mime-types 2.4.3
Using mini_portile 0.6.2
Using multimap 1.1.3
Using nokogiri 1.6.6.2
Using oauth 0.4.7
Using rack 1.6.0
Using rack-protection 1.5.3
Using rspec-support 3.1.2
Using rspec-core 3.1.7
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using rspec 3.1.0
Using simple_oauth 0.2.0
Using tilt 1.4.1
Using sinatra 1.4.5
Using sqlite3 1.3.10
Using twitter 5.3.1
Using twitter_oauth 0.4.94
Using vcr 2.9.3
Using webmock 1.20.4
Using bundler 1.7.12
Your bundle is updated!```

Doing `bundle update twitter`gives the same results.

**Comment by MarwoodChap** [comment]
I've tried uninstalling and reinstalling the twitter gem.

On the uninstall I apparently had two versions of twitter 4.8.1 and 5.3.1. I uninstalled both and then ran bundle update. Gave me the same error.

Checking the uninstall again it reports I still have the same two versions. Doing an uninstall of the earlier version doesn't seem to actually remove it.

Am I on the right lines here? Is there a way of removing all but the version of the gem Slogger needs?

— James

**Comment by ttscoff** [comment]
You can try running `gem install twitter -v 5.3.1` (may need to use 
sudo)

**Comment by MarwoodChap** [comment]
That didn't seem to work. The install succeeded but I'm getting the same error.

**Comment by MarwoodChap** [comment]
I'm still stumped by this. Is there a way to perhaps remove the offending gems/scripts and start again?

**Comment by ttscoff** [comment]
You'd have to uninstall the gems individually (gem uninstall ...) unless 
you're using RVM or rbenv. You can try `bundle clean` and `bundle 
update` to see if that helps at all. What errors are you seeing at this 
point?

**Comment by MarwoodChap** [comment]
I'm getting the same error with twitter:

```TwitterLogger: Getting Twitter timeline for marwoodchap
/Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:74:in `get_tweets': undefined method `configure' for Twitter:Module (NoMethodError)
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:237:in `block (2 levels) in do_log'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:262:in `try'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:237:in `block in do_log'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:235:in `each'
	from /Users/jamesmarwood/Documents/Slogger-master/plugins/twitterlogger.rb:235:in `do_log'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:284:in `block in run_plugins'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:271:in `each'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:271:in `run_plugins'
	from /Users/jamesmarwood/Documents/Slogger-master/slogger.rb:460:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./slogger:18:in `<main>'
```

However, I tried ```bundle clean``` and that asked me to either set a path or use --force. I tried the latter and got this error:

```Jamess-Mac-mini:slogger-master jamesmarwood$ bundle clean --force
Removing faraday (0.8.7)
Removing json (1.8.0)
Removing magickwand (0.2.0)
Removing mime-types (1.23)
Removing multi_json (1.7.7)
Removing multipart-post (1.2.0)
Removing rake (0.9.6)
Removing rdoc (4.0.0)
Removing rmagick (2.13.4)
Removing simple-rss (1.2.3)
Removing test-unit (2.0.0.0)
Removing twitter (4.8.1)
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1433:in `unlink': Permission denied - /Library/Ruby/Gems/2.0.0/cache/faraday-0.8.7.gem (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1433:in `block in remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1438:in `platform_support'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1432:in `remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:785:in `remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:563:in `block in rm'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `rm'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:206:in `block in clean'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:206:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:206:in `clean'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/cli/clean.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/cli.rb:349:in `clean'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/cli.rb:9:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/bin/bundle:20:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.12/bin/bundle:18:in `<top (required)>'
	from /usr/bin/bundle:23:in `load'
	from /usr/bin/bundle:23:in `<main>'```

I'm assuming my twitter install has gone wonky…

**Comment by ttscoff** [comment]
You can bypass the permissions error by using `sudo bundle clean 
--force`, although it may cause issues in any other ruby-based scripts 
that have gem dependencies. I think I would suggest running `sudo gem 
uninstall faraday` and then just running `bundle clean --force` again.

Note that this may not solve the Twitter issues at all, but starting 
clean is a decent step in locating the problem.

**Comment by MarwoodChap** [comment]
I uninstalled faraday, and the gems dependent on it (faraday middleware, twitter and instagram).

I then ran ```bundle clean --force``` but got the error ```Could not find faraday-0.9.1 in any of the sources```

Running bundle update just puts me back in the same place - installs the missing gems but slogger fails with the error above.

**Comment by ttscoff** [comment]
If you run `bundle show`, does twitter_oauth (0.4.94) show up?

**Comment by MarwoodChap** [comment]
No, I get an error about the lack of faraday

```Jamess-Mac-mini:slogger-master jamesmarwood$ bundle show
Gems included by the bundle:
Could not find faraday-0.9.1 in any of the sources
```

**Comment by ttscoff** [comment]
Hm. Try forcing the install of faraday with `sudo gem install faraday -v 
0.9.1`.

**Comment by MarwoodChap** [comment]
I've done that, and got the same error for faraday_middleware 0.9.1, Instagram 1.1.3 and then twitter 5.3.1.

I reinstalled each with the ```sudo gem install xxx -vx.x.x''' command and I seem to be back where I was, with the previous error.

**Comment by ttscoff** [comment]
Note that the twitter gem and the twitter_oauth gem are two different 
things. Have you ensured the correct version of twitter_oauth?

-Brett

**Comment by MarwoodChap** [comment]
I've got version 0.4.94.

As far as I can tell it has authorised - I did go through the process of getting the redirect to the API key and pasting that in. Is it worth replacing the twitter logger file and doing that again?

**Comment by ttscoff** [comment]
No, that won't make a difference. I'm pretty stumped on this one.

**Comment by MarwoodChap** [comment]
Well, that's a claim to fame at least :)

Is there a way I can nuke the lot and start again?

**Comment by ttscoff** [comment]
Try just cloning (or downloading and unzipping) slogger from the repo 
into a new directory and running the bundle install again. I haven't 
done this with the root Ruby install for a long time; I use RVM which 
keeps my gems separate for each directory, so I can't remember how it's 
handled without a version manager.

Note that the development branch might offer different results: 
https://github.com/ttscoff/Slogger/tree/develop

-Brett

**Comment by MarwoodChap** [comment]
I’ll give that a go this evening then.

Thanks for your help Brett :)





On 6 February 2015 at 17:30:55, Brett Terpstra (notifications@github.com) wrote:

Try just cloning (or downloading and unzipping) slogger from the repo
into a new directory and running the bundle install again. I haven't
done this with the root Ruby install for a long time; I use RVM which
keeps my gems separate for each directory, so I can't remember how it's
handled without a version manager.

Note that the development branch might offer different results:
https://github.com/ttscoff/Slogger/tree/develop

-Brett

**Comment by MarwoodChap** [comment]
That seems to have worked. I think I made a really stupid error on the first install, and edited the plug-in file rather than the config.

Thanks again for your help Brett, and especially for your patience :)

**Comment by ttscoff** [comment]
Awesome, glad to hear it.
