### ISSUE TITLE
Ruby seems to be causing an issue? 

### ISSUE THREAD

**Issue by blackoctopus** [ttscoff/Slogger#374]
Don't know what changed but I get this error now.

```
Initializing Slogger v2 (2.1.14)...
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri (LoadError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/philipmozolak/Desktop/Slogger2/plugins/misologger.rb:13:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/philipmozolak/Desktop/Slogger2/slogger.rb:268:in `block in run_plugins'
	from /Users/philipmozolak/Desktop/Slogger2/slogger.rb:260:in `each'
	from /Users/philipmozolak/Desktop/Slogger2/slogger.rb:260:in `run_plugins'
	from /Users/philipmozolak/Desktop/Slogger2/slogger.rb:460:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/philipmozolak/Desktop/Slogger2/slogger:18:in `<main>'
logout
```

**Comment by larryhynes** [comment]
It looks like it's having trouble finding the nokogiri gem. Have you tried `bundle install` in the Slogger directory, or `gem install nokogiri`? It might also be a version conflict.

**Comment by emory** [comment]
(if that works and still isn't running try `bundle exec slogger`)
