### ISSUE TITLE
Twitter logger error under 10.11 beta?

### ISSUE THREAD

**Issue by jgclark** [ttscoff/Slogger#381]
I've just loaded up El Capitan (OS X 10.11) public beta 1. All my current loggers worked OK, except Twitter.  This is the error message I got repeated a few times:

```
  22:38:05        TwitterLogger: Getting Twitter timeline for jgctweets
Faraday::Builder is now Faraday::RackBuilder.
/Library/Ruby/Gems/2.0.0/gems/twitter-5.3.1/lib/twitter/tweet.rb:84:in `uris': To get urls, you must pass `:include_entities => true` when requesting the Twitter::Tweet.
/Library/Ruby/Gems/2.0.0/gems/twitter-5.3.1/lib/twitter/tweet.rb:57:in `media': To get media, you must pass `:include_entities => true` when requesting the Twitter::Tweet.
```
However, the entry lands up in DayOne OK, so this clearly isn't a big deal.

**Comment by stevemoser** [comment]
I see this as well but I'm on 10.10. So I think it is specific to twitter and/or gem and not 10.11.

**Comment by jgclark** [comment]
I've tried this again, and it now appears fine under 10.11 public beta 1.  I've checked the gem versions, in case @stevemoser is on something different:

- twitter (5.14.0, 5.3.1)
- twitter_oauth (0.4.94)

And I'm running slogger after `rvm use system` which sets up ruby v2.0.0p645.

**Comment by jgclark** [comment]
Now I'm really confused. I'm back to having my original error message.
